package com.example.wazitoecommerce.navigation

const val ROUT_HOME = "home"
const val ROUT_LOGIN = "login"
const val ROUT_SIGNUP = "signup"
const val ROUT_DASHBOARD = "dashboard"
const val ROUT_ABOUT = "about"
const val ROUT_BEAUTY = "beauty"
const val ROUT_SPLASH = "splash"
const val ROUT_SERVICES = "services"
const val ROUT_CLOTHING = "clothing"
const val ROUT_ELECTRONIC= "electronic"
const val ROUT_PHARMACY= "pharmacy"
const val ROUT_GROCERIES= "groceries"
const val ROUT_ADDPRODUCT= "addproduct"
const val ROUT_VIEWRODUCT= "viewproduct"
